# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/mode4_test/rfdc_multi_cores_mode4/myproj/myproj.srcs/sources_1/ip/RFDC_MODE4/RFDC_MODE4.xci
# IP: The module: 'RFDC_MODE4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/mode4_test/rfdc_multi_cores_mode4/myproj/myproj.srcs/sources_1/ip/RFDC_MODE4/synth/RFDC_MODE4.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/mode4_test/rfdc_multi_cores_mode4/myproj/myproj.srcs/sources_1/ip/RFDC_MODE4/synth/RFDC_MODE4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/mode4_test/rfdc_multi_cores_mode4/myproj/myproj.srcs/sources_1/ip/RFDC_MODE4/synth/RFDC_MODE4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/mode4_test/rfdc_multi_cores_mode4/myproj/myproj.srcs/sources_1/ip/RFDC_MODE4/RFDC_MODE4.xci
# IP: The module: 'RFDC_MODE4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/mode4_test/rfdc_multi_cores_mode4/myproj/myproj.srcs/sources_1/ip/RFDC_MODE4/synth/RFDC_MODE4.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/mode4_test/rfdc_multi_cores_mode4/myproj/myproj.srcs/sources_1/ip/RFDC_MODE4/synth/RFDC_MODE4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/mode4_test/rfdc_multi_cores_mode4/myproj/myproj.srcs/sources_1/ip/RFDC_MODE4/synth/RFDC_MODE4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
