# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode2/4096GSps/rfdc_two_adc_4096gsps/myproj/myproj.srcs/sources_1/ip/rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2/rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2.xci
# IP: The module: 'rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode2/4096GSps/rfdc_two_adc_4096gsps/myproj/myproj.srcs/sources_1/ip/rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2/rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode2/4096GSps/rfdc_two_adc_4096gsps/myproj/myproj.srcs/sources_1/ip/rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2/rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2.xci
# IP: The module: 'rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode2/4096GSps/rfdc_two_adc_4096gsps/myproj/myproj.srcs/sources_1/ip/rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2/rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_two_adc_4096gsps_c_counter_binary_v12_0_i2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
