# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode4/2048GSps_MTS/rfdc_multi_eight_adcs_2048gsps_mts/myproj/myproj.srcs/sources_1/ip/ADC8_R2R_MTS_2048/ADC8_R2R_MTS_2048.xci
# IP: The module: 'ADC8_R2R_MTS_2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode4/2048GSps_MTS/rfdc_multi_eight_adcs_2048gsps_mts/myproj/myproj.srcs/sources_1/ip/ADC8_R2R_MTS_2048/synth/ADC8_R2R_MTS_2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC8_R2R_MTS_2048'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode4/2048GSps_MTS/rfdc_multi_eight_adcs_2048gsps_mts/myproj/myproj.srcs/sources_1/ip/ADC8_R2R_MTS_2048/synth/ADC8_R2R_MTS_2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC8_R2R_MTS_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode4/2048GSps_MTS/rfdc_multi_eight_adcs_2048gsps_mts/myproj/myproj.srcs/sources_1/ip/ADC8_R2R_MTS_2048/synth/ADC8_R2R_MTS_2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC8_R2R_MTS_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode4/2048GSps_MTS/rfdc_multi_eight_adcs_2048gsps_mts/myproj/myproj.srcs/sources_1/ip/ADC8_R2R_MTS_2048/ADC8_R2R_MTS_2048.xci
# IP: The module: 'ADC8_R2R_MTS_2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode4/2048GSps_MTS/rfdc_multi_eight_adcs_2048gsps_mts/myproj/myproj.srcs/sources_1/ip/ADC8_R2R_MTS_2048/synth/ADC8_R2R_MTS_2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC8_R2R_MTS_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode4/2048GSps_MTS/rfdc_multi_eight_adcs_2048gsps_mts/myproj/myproj.srcs/sources_1/ip/ADC8_R2R_MTS_2048/synth/ADC8_R2R_MTS_2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC8_R2R_MTS_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode4/2048GSps_MTS/rfdc_multi_eight_adcs_2048gsps_mts/myproj/myproj.srcs/sources_1/ip/ADC8_R2R_MTS_2048/synth/ADC8_R2R_MTS_2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC8_R2R_MTS_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
