# Note: This file is produced automatically, and will be overwritten the next
# time you press "Generate" in System Generator. 
#


namespace eval ::xilinx::dsp::planaheaddriver {
	set Compilation {HDL Netlist}
	set CompilationFlow {STANDARD}
	set DSPDevice {xczu28dr}
	set DSPFamily {zynquplus}
	set DSPPackage {ffvg1517}
	set DSPSpeed {-2-e}
	set FPGAClockPeriod 3.9062
	set GenerateTestBench 0
	set HDLLanguage {vhdl}
	set IPOOCCacheRootPath {/home/wei/.Xilinx/Sysgen/SysgenVivado/lnx64.o/ip}
	set ImplStrategyName {Vivado Implementation Defaults}
	set Project {tengbe_test}
	set ProjectFiles {
		{{conv_pkg.vhd} -lib {xil_defaultlib}}
		{{synth_reg.vhd} -lib {xil_defaultlib}}
		{{synth_reg_w_init.vhd} -lib {xil_defaultlib}}
		{{srl17e.vhd} -lib {xil_defaultlib}}
		{{srl33e.vhd} -lib {xil_defaultlib}}
		{{synth_reg_reg.vhd} -lib {xil_defaultlib}}
		{{single_reg_w_init.vhd} -lib {xil_defaultlib}}
		{{xlclockdriver_rd.vhd} -lib {xil_defaultlib}}
		{{vivado_ip.tcl}}
		{{tengbe_test_entity_declarations.vhd} -lib {xil_defaultlib}}
		{{tengbe_test.vhd} -lib {xil_defaultlib}}
		{{tengbe_test_clock.xdc}}
		{{tengbe_test.xdc}}
	}
	set SimPeriod 1
	set SimTime 10
	set SimulationTime {242.96820000 ns}
	set SynthStrategyName {Vivado Synthesis Defaults}
	set SynthesisTool {Vivado}
	set TargetDir {/home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/sysgen}
	set TopLevelModule {tengbe_test}
	set TopLevelSimulinkHandle 76623
	set VHDLLib {xil_defaultlib}
	set TopLevelPortInterface {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out Name {tengbe_test_tx_snapshot_ss_ctrl_user_data_out}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out Width 32
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out DatFile {tengbe_test_tx_snapshot_ss_ctrl_tengbe_test_tx_snapshot_ss_ctrl_user_data_out.dat}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out IconText {tengbe_test_tx_snapshot_ss_ctrl_user_data_out}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out Direction in
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out Period 1
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out Interface 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out Locs {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_ctrl_user_data_out IOStandard {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out Name {tengbe_test_tx_snapshot_ss_bram_data_out}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out Width 32
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out DatFile {tengbe_test_tx_snapshot_ss_bram_tengbe_test_tx_snapshot_ss_bram_data_out.dat}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out IconText {tengbe_test_tx_snapshot_ss_bram_data_out}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out Direction in
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out Period 1
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out Interface 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out Locs {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_out IOStandard {}
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out Name {tengbe_test_rst_user_data_out}
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out Width 32
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out DatFile {tengbe_test_rst_tengbe_test_rst_user_data_out.dat}
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out IconText {tengbe_test_rst_user_data_out}
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out Direction in
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out Period 1
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out Interface 0
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out Locs {}
	dict set TopLevelPortInterface tengbe_test_rst_user_data_out IOStandard {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out Name {tengbe_test_pkt_sim_period_user_data_out}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out Width 32
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out DatFile {tengbe_test_pkt_sim_period_tengbe_test_pkt_sim_period_user_data_out.dat}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out IconText {tengbe_test_pkt_sim_period_user_data_out}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out Direction in
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out Period 1
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out Interface 0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out Locs {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_period_user_data_out IOStandard {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out Name {tengbe_test_pkt_sim_payload_len_user_data_out}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out Width 32
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out DatFile {tengbe_test_pkt_sim_payload_len_tengbe_test_pkt_sim_payload_len_user_data_out.dat}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out IconText {tengbe_test_pkt_sim_payload_len_user_data_out}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out Direction in
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out Period 1
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out Interface 0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out Locs {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_payload_len_user_data_out IOStandard {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out Name {tengbe_test_pkt_sim_enable_user_data_out}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out Width 32
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out DatFile {tengbe_test_pkt_sim_enable_tengbe_test_pkt_sim_enable_user_data_out.dat}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out IconText {tengbe_test_pkt_sim_enable_user_data_out}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out Direction in
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out Period 1
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out Interface 0
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out Locs {}
	dict set TopLevelPortInterface tengbe_test_pkt_sim_enable_user_data_out IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow Name {tengbe_test_gbe0_tx_overflow}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow DatFile {tengbe_test_gbe0_tengbe_test_gbe0_tx_overflow.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow IconText {tengbe_test_gbe0_tx_overflow}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_overflow IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull Name {tengbe_test_gbe0_tx_afull}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull DatFile {tengbe_test_gbe0_tengbe_test_gbe0_tx_afull.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull IconText {tengbe_test_gbe0_tx_afull}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_afull IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid Name {tengbe_test_gbe0_rx_valid}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_valid.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid IconText {tengbe_test_gbe0_rx_valid}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_valid IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port Name {tengbe_test_gbe0_rx_source_port}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port Type UFix_16_0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port Width 16
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_source_port.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port IconText {tengbe_test_gbe0_rx_source_port}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_port IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip Name {tengbe_test_gbe0_rx_source_ip}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_source_ip.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip IconText {tengbe_test_gbe0_rx_source_ip}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_source_ip IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun Name {tengbe_test_gbe0_rx_overrun}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_overrun.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun IconText {tengbe_test_gbe0_rx_overrun}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame Name {tengbe_test_gbe0_rx_end_of_frame}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_end_of_frame.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame IconText {tengbe_test_gbe0_rx_end_of_frame}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_end_of_frame IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data Name {tengbe_test_gbe0_rx_data}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data Type UFix_64_0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data Width 64
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_data.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data IconText {tengbe_test_gbe0_rx_data}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_data IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame Name {tengbe_test_gbe0_rx_bad_frame}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_bad_frame.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame IconText {tengbe_test_gbe0_rx_bad_frame}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_bad_frame IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up Name {tengbe_test_gbe0_led_up}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up DatFile {tengbe_test_gbe0_tengbe_test_gbe0_led_up.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up IconText {tengbe_test_gbe0_led_up}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_up IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx Name {tengbe_test_gbe0_led_tx}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx DatFile {tengbe_test_gbe0_tengbe_test_gbe0_led_tx.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx IconText {tengbe_test_gbe0_led_tx}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_tx IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx Name {tengbe_test_gbe0_led_rx}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx DatFile {tengbe_test_gbe0_tengbe_test_gbe0_led_rx.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx IconText {tengbe_test_gbe0_led_rx}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx Direction in
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_led_rx IOStandard {}
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out Name {tengbe_test_dest_port_user_data_out}
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out Width 32
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out DatFile {tengbe_test_dest_port_tengbe_test_dest_port_user_data_out.dat}
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out IconText {tengbe_test_dest_port_user_data_out}
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out Direction in
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out Period 1
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out Interface 0
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out Locs {}
	dict set TopLevelPortInterface tengbe_test_dest_port_user_data_out IOStandard {}
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out Name {tengbe_test_dest_ip_user_data_out}
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out Width 32
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out DatFile {tengbe_test_dest_ip_tengbe_test_dest_ip_user_data_out.dat}
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out IconText {tengbe_test_dest_ip_user_data_out}
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out Direction in
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out Period 1
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out Interface 0
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out Locs {}
	dict set TopLevelPortInterface tengbe_test_dest_ip_user_data_out IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rst Name {tengbe_test_gbe0_rst}
	dict set TopLevelPortInterface tengbe_test_gbe0_rst Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_rst ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rst BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rst Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rst DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rst.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rst IconText {tengbe_test_gbe0_rst}
	dict set TopLevelPortInterface tengbe_test_gbe0_rst Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_rst Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rst Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rst InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rst InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rst ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rst Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rst IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack Name {tengbe_test_gbe0_rx_ack}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_ack.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack IconText {tengbe_test_gbe0_rx_ack}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_ack IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack Name {tengbe_test_gbe0_rx_overrun_ack}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack DatFile {tengbe_test_gbe0_tengbe_test_gbe0_rx_overrun_ack.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack IconText {tengbe_test_gbe0_rx_overrun_ack}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rx_overrun_ack IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data Name {tengbe_test_gbe0_tx_data}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data Type UFix_64_0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data Width 64
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data DatFile {tengbe_test_gbe0_tengbe_test_gbe0_tx_data.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data IconText {tengbe_test_gbe0_tx_data}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_data IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip Name {tengbe_test_gbe0_tx_dest_ip}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip DatFile {tengbe_test_gbe0_tengbe_test_gbe0_tx_dest_ip.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip IconText {tengbe_test_gbe0_tx_dest_ip}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_ip IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port Name {tengbe_test_gbe0_tx_dest_port}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port Type UFix_16_0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port Width 16
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port DatFile {tengbe_test_gbe0_tengbe_test_gbe0_tx_dest_port.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port IconText {tengbe_test_gbe0_tx_dest_port}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_dest_port IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame Name {tengbe_test_gbe0_tx_end_of_frame}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame DatFile {tengbe_test_gbe0_tengbe_test_gbe0_tx_end_of_frame.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame IconText {tengbe_test_gbe0_tx_end_of_frame}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_end_of_frame IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid Name {tengbe_test_gbe0_tx_valid}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid Type Bool
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid Width 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid DatFile {tengbe_test_gbe0_tengbe_test_gbe0_tx_valid.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid IconText {tengbe_test_gbe0_tx_valid}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_valid IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in Name {tengbe_test_gbe0_rxbadctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in DatFile {tengbe_test_gbe0_rxbadctr_tengbe_test_gbe0_rxbadctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in IconText {tengbe_test_gbe0_rxbadctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxbadctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in Name {tengbe_test_gbe0_rxctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in DatFile {tengbe_test_gbe0_rxctr_tengbe_test_gbe0_rxctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in IconText {tengbe_test_gbe0_rxctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in Name {tengbe_test_gbe0_rxeofctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in DatFile {tengbe_test_gbe0_rxeofctr_tengbe_test_gbe0_rxeofctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in IconText {tengbe_test_gbe0_rxeofctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxeofctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in Name {tengbe_test_gbe0_rxofctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in DatFile {tengbe_test_gbe0_rxofctr_tengbe_test_gbe0_rxofctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in IconText {tengbe_test_gbe0_rxofctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxofctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in Name {tengbe_test_gbe0_rxvldctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in DatFile {tengbe_test_gbe0_rxvldctr_tengbe_test_gbe0_rxvldctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in IconText {tengbe_test_gbe0_rxvldctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_rxvldctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in Name {tengbe_test_gbe0_txctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in DatFile {tengbe_test_gbe0_txctr_tengbe_test_gbe0_txctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in IconText {tengbe_test_gbe0_txctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in Name {tengbe_test_gbe0_txfullctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in DatFile {tengbe_test_gbe0_txfullctr_tengbe_test_gbe0_txfullctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in IconText {tengbe_test_gbe0_txfullctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txfullctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in Name {tengbe_test_gbe0_txofctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in DatFile {tengbe_test_gbe0_txofctr_tengbe_test_gbe0_txofctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in IconText {tengbe_test_gbe0_txofctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txofctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in Name {tengbe_test_gbe0_txvldctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in DatFile {tengbe_test_gbe0_txvldctr_tengbe_test_gbe0_txvldctr_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in IconText {tengbe_test_gbe0_txvldctr_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_txvldctr_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in Name {tengbe_test_gbe0_linkup_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in DatFile {tengbe_test_gbe0_linkup_tengbe_test_gbe0_linkup_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in IconText {tengbe_test_gbe0_linkup_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_linkup_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in Name {tengbe_test_gbe0_tx_cnt_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in DatFile {tengbe_test_gbe0_tx_cnt_tengbe_test_gbe0_tx_cnt_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in IconText {tengbe_test_gbe0_tx_cnt_user_data_in}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_gbe0_tx_cnt_user_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway Name {tengbe_test_led0_gbe0_pulse_tx_gateway}
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway Type Bool
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway Width 1
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway DatFile {tengbe_test_led0_gbe0_pulse_tx_tengbe_test_led0_gbe0_pulse_tx_gateway.dat}
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway IconText {tengbe_test_led0_gbe0_pulse_tx_gateway}
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway Direction out
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway Period 1
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway Interface 0
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway Locs {}
	dict set TopLevelPortInterface tengbe_test_led0_gbe0_pulse_tx_gateway IOStandard {}
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway Name {tengbe_test_led1_gbe0_up_gateway}
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway Type Bool
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway Width 1
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway DatFile {tengbe_test_led1_gbe0_up_tengbe_test_led1_gbe0_up_gateway.dat}
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway IconText {tengbe_test_led1_gbe0_up_gateway}
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway Direction out
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway Period 1
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway Interface 0
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway Locs {}
	dict set TopLevelPortInterface tengbe_test_led1_gbe0_up_gateway IOStandard {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr Name {tengbe_test_tx_snapshot_ss_bram_addr}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr Type UFix_12_0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr Width 12
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr DatFile {tengbe_test_tx_snapshot_ss_bram_tengbe_test_tx_snapshot_ss_bram_addr.dat}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr IconText {tengbe_test_tx_snapshot_ss_bram_addr}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr Direction out
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr Period 1
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr Interface 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr Locs {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_addr IOStandard {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in Name {tengbe_test_tx_snapshot_ss_bram_data_in}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in DatFile {tengbe_test_tx_snapshot_ss_bram_tengbe_test_tx_snapshot_ss_bram_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in IconText {tengbe_test_tx_snapshot_ss_bram_data_in}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_data_in IOStandard {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we Name {tengbe_test_tx_snapshot_ss_bram_we}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we Type UFix_1_0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we Width 1
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we DatFile {tengbe_test_tx_snapshot_ss_bram_tengbe_test_tx_snapshot_ss_bram_we.dat}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we IconText {tengbe_test_tx_snapshot_ss_bram_we}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we Direction out
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we Period 1
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we Interface 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we Locs {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_bram_we IOStandard {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in Name {tengbe_test_tx_snapshot_ss_status_user_data_in}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in Width 32
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in DatFile {tengbe_test_tx_snapshot_ss_status_tengbe_test_tx_snapshot_ss_status_user_data_in.dat}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in IconText {tengbe_test_tx_snapshot_ss_status_user_data_in}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in Direction out
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in Period 1
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in Interface 0
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in InterfaceName {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in ClockDomain {tengbe_test}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in Locs {}
	dict set TopLevelPortInterface tengbe_test_tx_snapshot_ss_status_user_data_in IOStandard {}
	dict set TopLevelPortInterface clk Name {clk}
	dict set TopLevelPortInterface clk Type -
	dict set TopLevelPortInterface clk ArithmeticType xlUnsigned
	dict set TopLevelPortInterface clk BinaryPoint 0
	dict set TopLevelPortInterface clk Width 1
	dict set TopLevelPortInterface clk DatFile {}
	dict set TopLevelPortInterface clk Direction in
	dict set TopLevelPortInterface clk Period 1
	dict set TopLevelPortInterface clk Interface 6
	dict set TopLevelPortInterface clk InterfaceName {}
	dict set TopLevelPortInterface clk InterfaceString {CLOCK}
	dict set TopLevelPortInterface clk ClockDomain {tengbe_test}
	dict set TopLevelPortInterface clk Locs {}
	dict set TopLevelPortInterface clk IOStandard {}
	dict set TopLevelPortInterface clk AssociatedInterfaces {}
	dict set TopLevelPortInterface clk AssociatedResets {}
	set MemoryMappedPort {}
}

source SgPaProject.tcl
::xilinx::dsp::planaheadworker::dsp_create_project