# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tengbe_test_c_counter_binary_v12_0_i2/tengbe_test_c_counter_binary_v12_0_i2.xci
# IP: The module: 'tengbe_test_c_counter_binary_v12_0_i2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tengbe_test_c_counter_binary_v12_0_i2/tengbe_test_c_counter_binary_v12_0_i2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tengbe_test_c_counter_binary_v12_0_i2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tengbe_test_c_counter_binary_v12_0_i2/tengbe_test_c_counter_binary_v12_0_i2.xci
# IP: The module: 'tengbe_test_c_counter_binary_v12_0_i2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tengbe_test_c_counter_binary_v12_0_i2/tengbe_test_c_counter_binary_v12_0_i2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tengbe_test_c_counter_binary_v12_0_i2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
