# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode1/4096GSps/rfdc_one_adc_4096gsps_no_led/myproj/myproj.srcs/sources_1/ip/rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1/rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1.xci
# IP: The module: 'rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode1/4096GSps/rfdc_one_adc_4096gsps_no_led/myproj/myproj.srcs/sources_1/ip/rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1/rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode1/4096GSps/rfdc_one_adc_4096gsps_no_led/myproj/myproj.srcs/sources_1/ip/rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1/rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1.xci
# IP: The module: 'rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_adc_cores/mode1/4096GSps/rfdc_one_adc_4096gsps_no_led/myproj/myproj.srcs/sources_1/ip/rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1/rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_one_adc_4096gsps_no_led_c_counter_binary_v12_0_i1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
