# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0/rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0.xci
# IP: The module: 'rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0/rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0/rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0.xci
# IP: The module: 'rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0/rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_multi_cores_mode2_c_counter_binary_v12_0_i0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
