# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/RFDC_MODE2/RFDC_MODE2.xci
# IP: The module: 'RFDC_MODE2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/RFDC_MODE2/synth/RFDC_MODE2.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/RFDC_MODE2/synth/RFDC_MODE2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/RFDC_MODE2/synth/RFDC_MODE2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/RFDC_MODE2/RFDC_MODE2.xci
# IP: The module: 'RFDC_MODE2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/RFDC_MODE2/synth/RFDC_MODE2.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/RFDC_MODE2/synth/RFDC_MODE2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/wei/casper/tutorials_devel/zcu111/rfdc_multi_cores/rfdc_multi_cores_mode2/myproj/myproj.srcs/sources_1/ip/RFDC_MODE2/synth/RFDC_MODE2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFDC_MODE2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
