// MODULE top, AUTOMATICALLY GENERATED BY PYTHON

/**/
`default_nettype wire


module top (
  // onegbe: one_gbe
    input onegbe_test_one_gbe_mgt_clk_n,
    input onegbe_test_one_gbe_mgt_clk_p,
    input onegbe_test_one_gbe_sfp_rx_n,
    input onegbe_test_one_gbe_sfp_rx_p,
    output onegbe_test_one_gbe_sfp_tx_n,
    output onegbe_test_one_gbe_sfp_tx_p,
  // zcu111: ZCU111
    input clk_100_n,
    input clk_100_p
  );




/*
  _____ _                   _     
 / ____(_)                 | |    
| (___  _  __ _ _ __   __ _| |___ 
 \___ \| |/ _` | '_ \ / _` | / __|
 ____) | | (_| | | | | (_| | \__ \ 
|_____/|_|\__, |_| |_|\__,_|_|___/
          __/ |                  
         |___/                   
*/
  // onegbe: one_gbe
  wire clk_200;
  wire gbe_gtpowergood;
  wire gbe_mgt_clk;
  wire gbe_mmcm_locked_out;
  wire gbe_rxuserclk2_out;
  wire gbe_rxuserclk_out;
  wire gbe_userclk2_out;
  wire gbe_userclk_out;
  wire [31:0] onegbe_test_one_gbe_app_dbg_data;
  wire onegbe_test_one_gbe_app_dbg_dvld;
  wire onegbe_test_one_gbe_app_rx_ack;
  wire onegbe_test_one_gbe_app_rx_badframe;
  wire [7:0] onegbe_test_one_gbe_app_rx_data;
  wire onegbe_test_one_gbe_app_rx_dvld;
  wire onegbe_test_one_gbe_app_rx_eof;
  wire onegbe_test_one_gbe_app_rx_overrun;
  wire onegbe_test_one_gbe_app_rx_rst;
  wire [31:0] onegbe_test_one_gbe_app_rx_srcip;
  wire [15:0] onegbe_test_one_gbe_app_rx_srcport;
  wire onegbe_test_one_gbe_app_tx_afull;
  wire [7:0] onegbe_test_one_gbe_app_tx_data;
  wire [31:0] onegbe_test_one_gbe_app_tx_destip;
  wire [15:0] onegbe_test_one_gbe_app_tx_destport;
  wire onegbe_test_one_gbe_app_tx_dvld;
  wire onegbe_test_one_gbe_app_tx_eof;
  wire onegbe_test_one_gbe_app_tx_overflow;
  wire onegbe_test_one_gbe_app_tx_rst;
  wire [7:0] onegbe_test_one_gbe_mac_gmii_rx_data;
  wire onegbe_test_one_gbe_mac_gmii_rx_dvld;
  wire onegbe_test_one_gbe_mac_gmii_rx_er;
  wire [7:0] onegbe_test_one_gbe_mac_gmii_tx_data;
  wire onegbe_test_one_gbe_mac_gmii_tx_en;
  wire onegbe_test_one_gbe_mac_gmii_tx_er;
  wire onegbe_test_one_gbe_mac_rx_badframe;
  wire [7:0] onegbe_test_one_gbe_mac_rx_data;
  wire onegbe_test_one_gbe_mac_rx_dvld;
  wire onegbe_test_one_gbe_mac_rx_goodframe;
  wire onegbe_test_one_gbe_mac_syncacquired;
  wire onegbe_test_one_gbe_mac_tx_ack;
  wire [7:0] onegbe_test_one_gbe_mac_tx_data;
  wire onegbe_test_one_gbe_mac_tx_dvld;
  wire [15:0] onegbe_test_one_gbe_phy_status;
  wire onegbe_test_one_gbe_reset_done;
  wire rst_125_out;
  wire sys_rst;
  // sw_reg: bitfield_snapshot/ss/ctrl
  wire [31:0] onegbe_test_bitfield_snapshot_ss_ctrl_out;
  wire [31:0] onegbe_test_bitfield_snapshot_ss_ctrl_user_data_out;
  // sw_reg: bitfield_snapshot/ss/status
  wire [31:0] onegbe_test_bitfield_snapshot_ss_status_in;
  wire [31:0] onegbe_test_bitfield_snapshot_ss_status_user_data_in;
  // sw_reg: dest_ip
  wire [31:0] onegbe_test_dest_ip_out;
  wire [31:0] onegbe_test_dest_ip_user_data_out;
  // sw_reg: dest_port
  wire [31:0] onegbe_test_dest_port_out;
  wire [31:0] onegbe_test_dest_port_user_data_out;
  // sw_reg: pkt_sim/enable
  wire [31:0] onegbe_test_pkt_sim_enable_out;
  wire [31:0] onegbe_test_pkt_sim_enable_user_data_out;
  // sw_reg: pkt_sim/payload_len
  wire [31:0] onegbe_test_pkt_sim_payload_len_out;
  wire [31:0] onegbe_test_pkt_sim_payload_len_user_data_out;
  // sw_reg: pkt_sim/period
  wire [31:0] onegbe_test_pkt_sim_period_out;
  wire [31:0] onegbe_test_pkt_sim_period_user_data_out;
  // sw_reg: rst
  wire [31:0] onegbe_test_rst_out;
  wire [31:0] onegbe_test_rst_user_data_out;
  // sys_block: xps:sys_block0
  wire axil_clk;
  wire axil_rst_n;
  wire [11:0] onegbe_test_bitfield_snapshot_ss_bram_addr;
  wire [31:0] onegbe_test_bitfield_snapshot_ss_bram_data_in;
  wire [31:0] onegbe_test_bitfield_snapshot_ss_bram_data_out;
  wire [0:0] onegbe_test_bitfield_snapshot_ss_bram_we;
  wire [0:0] onegbe_test_bitfield_snapshot_ss_ctrl_out_we;
  wire [0:0] onegbe_test_bitfield_snapshot_ss_status_in_we;
  wire [0:0] onegbe_test_dest_ip_out_we;
  wire [0:0] onegbe_test_dest_port_out_we;
  wire [31:0] onegbe_test_one_gbe_out;
  wire [0:0] onegbe_test_one_gbe_out_we;
  wire [0:0] onegbe_test_pkt_sim_enable_out_we;
  wire [0:0] onegbe_test_pkt_sim_payload_len_out_we;
  wire [0:0] onegbe_test_pkt_sim_period_out_we;
  wire [0:0] onegbe_test_rst_out_we;
  wire [31:0] onegbe_test_sys_board_id_in;
  wire [0:0] onegbe_test_sys_board_id_in_we;
  wire [31:0] onegbe_test_sys_clkcounter_in;
  wire [0:0] onegbe_test_sys_clkcounter_in_we;
  wire [31:0] onegbe_test_sys_rev_in;
  wire [0:0] onegbe_test_sys_rev_in_we;
  wire [31:0] onegbe_test_sys_rev_rcs_in;
  wire [0:0] onegbe_test_sys_rev_rcs_in_we;
  wire [31:0] onegbe_test_sys_scratchpad_out;
  wire [0:0] onegbe_test_sys_scratchpad_out_we;
  // xsg: ZCU111
  wire user_clk;
  wire user_clk180;
  wire user_clk270;
  wire user_clk90;
  // zcu111: ZCU111
  wire [39:0] M_AXI_RFDC_araddr;
  wire [2:0] M_AXI_RFDC_arprot;
  wire M_AXI_RFDC_arready;
  wire M_AXI_RFDC_arvalid;
  wire [39:0] M_AXI_RFDC_awaddr;
  wire [2:0] M_AXI_RFDC_awprot;
  wire M_AXI_RFDC_awready;
  wire M_AXI_RFDC_awvalid;
  wire M_AXI_RFDC_bready;
  wire [1:0] M_AXI_RFDC_bresp;
  wire M_AXI_RFDC_bvalid;
  wire [31:0] M_AXI_RFDC_rdata;
  wire M_AXI_RFDC_rready;
  wire [1:0] M_AXI_RFDC_rresp;
  wire M_AXI_RFDC_rvalid;
  wire [31:0] M_AXI_RFDC_wdata;
  wire M_AXI_RFDC_wready;
  wire [3:0] M_AXI_RFDC_wstrb;
  wire M_AXI_RFDC_wvalid;
  wire [39:0] M_AXI_araddr;
  wire [2:0] M_AXI_arprot;
  wire M_AXI_arready;
  wire M_AXI_arvalid;
  wire [39:0] M_AXI_awaddr;
  wire [2:0] M_AXI_awprot;
  wire M_AXI_awready;
  wire M_AXI_awvalid;
  wire M_AXI_bready;
  wire [1:0] M_AXI_bresp;
  wire M_AXI_bvalid;
  wire [31:0] M_AXI_rdata;
  wire M_AXI_rready;
  wire [1:0] M_AXI_rresp;
  wire M_AXI_rvalid;
  wire [31:0] M_AXI_wdata;
  wire M_AXI_wready;
  wire [3:0] M_AXI_wstrb;
  wire M_AXI_wvalid;
  wire axil_rst;
  wire sys_clk;
  wire sys_clk180;
  wire sys_clk270;
  wire sys_clk90;
  wire sys_clk_rst;

/*
  _____           _                            
 |_   _|         | |                           
   | |  _ __  ___| |_ __ _ _ __   ___ ___  ___ 
   | | | '_ \/ __| __/ _` | '_ \ / __/ _ \/ __|
  _| |_| | | \__ \ || (_| | | | | (_|  __/\__ \ 
 |_____|_| |_|___/\__\__,_|_| |_|\___\___||___/
*/
  // onegbe: one_gbe
  gbe_udp #(
    .CPU_PROMISCUOUS(1),
    .DIS_CPU_RX(0),
    .DIS_CPU_TX(0),
    .LOCAL_ENABLE(1),
    .LOCAL_GATEWAY(32'd1),
    .LOCAL_IP(32'd3232246026),
    .LOCAL_MAC(48'd20015998343868),
    .LOCAL_PORT(16'd4321)
  ) onegbe_test_one_gbe (
    .app_clk(user_clk),
    .app_dbg_data(onegbe_test_one_gbe_app_dbg_data),
    .app_dbg_dvld(onegbe_test_one_gbe_app_dbg_dvld),
    .app_rx_ack(onegbe_test_one_gbe_app_rx_ack),
    .app_rx_badframe(onegbe_test_one_gbe_app_rx_badframe),
    .app_rx_data(onegbe_test_one_gbe_app_rx_data),
    .app_rx_dvld(onegbe_test_one_gbe_app_rx_dvld),
    .app_rx_eof(onegbe_test_one_gbe_app_rx_eof),
    .app_rx_overrun(onegbe_test_one_gbe_app_rx_overrun),
    .app_rx_rst(onegbe_test_one_gbe_app_rx_rst),
    .app_rx_srcip(onegbe_test_one_gbe_app_rx_srcip),
    .app_rx_srcport(onegbe_test_one_gbe_app_rx_srcport),
    .app_tx_afull(onegbe_test_one_gbe_app_tx_afull),
    .app_tx_data(onegbe_test_one_gbe_app_tx_data),
    .app_tx_destip(onegbe_test_one_gbe_app_tx_destip),
    .app_tx_destport(onegbe_test_one_gbe_app_tx_destport),
    .app_tx_dvld(onegbe_test_one_gbe_app_tx_dvld),
    .app_tx_eof(onegbe_test_one_gbe_app_tx_eof),
    .app_tx_overflow(onegbe_test_one_gbe_app_tx_overflow),
    .app_tx_rst(onegbe_test_one_gbe_app_tx_rst),
    .mac_rx_badframe(onegbe_test_one_gbe_mac_rx_badframe),
    .mac_rx_clk(gbe_userclk2_out),
    .mac_rx_data(onegbe_test_one_gbe_mac_rx_data),
    .mac_rx_dvld(onegbe_test_one_gbe_mac_rx_dvld),
    .mac_rx_goodframe(onegbe_test_one_gbe_mac_rx_goodframe),
    .mac_rx_rst(rst_125_out),
    .mac_syncacquired(onegbe_test_one_gbe_mac_syncacquired),
    .mac_tx_ack(onegbe_test_one_gbe_mac_tx_ack),
    .mac_tx_clk(gbe_userclk2_out),
    .mac_tx_data(onegbe_test_one_gbe_mac_tx_data),
    .mac_tx_dvld(onegbe_test_one_gbe_mac_tx_dvld),
    .mac_tx_rst(rst_125_out)
  );


  gig_eth_mac #(
    .MAX_FRAME_SIZE_JUMBO(9022),
    .MAX_FRAME_SIZE_STANDARD(1522)
  ) onegbe_test_one_gbe_mac (
    .conf_rx_en(1),
    .conf_rx_jumbo_en(0),
    .conf_rx_no_chk_crc(0),
    .conf_tx_en(1),
    .conf_tx_jumbo_en(0),
    .conf_tx_no_gen_crc(0),
    .gmii_col(0),
    .gmii_crs(0),
    .gmii_rx_data(onegbe_test_one_gbe_mac_gmii_rx_data),
    .gmii_rx_dvld(onegbe_test_one_gbe_mac_gmii_rx_dvld),
    .gmii_rx_er(onegbe_test_one_gbe_mac_gmii_rx_er),
    .gmii_tx_data(onegbe_test_one_gbe_mac_gmii_tx_data),
    .gmii_tx_en(onegbe_test_one_gbe_mac_gmii_tx_en),
    .gmii_tx_er(onegbe_test_one_gbe_mac_gmii_tx_er),
    .mac_rx_badframe(onegbe_test_one_gbe_mac_rx_badframe),
    .mac_rx_data(onegbe_test_one_gbe_mac_rx_data),
    .mac_rx_dvld(onegbe_test_one_gbe_mac_rx_dvld),
    .mac_rx_goodframe(onegbe_test_one_gbe_mac_rx_goodframe),
    .mac_tx_ack(onegbe_test_one_gbe_mac_tx_ack),
    .mac_tx_data(onegbe_test_one_gbe_mac_tx_data),
    .mac_tx_dvld(onegbe_test_one_gbe_mac_tx_dvld),
    .mac_tx_underrun(0),
    .reset(rst_125_out),
    .rx_clk(gbe_userclk2_out),
    .tx_clk(gbe_userclk2_out)
  );


  gig_ethernet_pcs_pma_autonegotiation_1000BASEX  onegbe_test_one_gbe_pcs_pma (
    .an_adv_config_vector(16'b1001100000000001),
    .an_interrupt(),
    .configuration_vector(5'b10000),
    .gmii_isolate(),
    .gmii_rx_dv(onegbe_test_one_gbe_mac_gmii_rx_dvld),
    .gmii_rx_er(onegbe_test_one_gbe_mac_gmii_rx_er),
    .gmii_rxd(onegbe_test_one_gbe_mac_gmii_rx_data),
    .gmii_tx_en(onegbe_test_one_gbe_mac_gmii_tx_en),
    .gmii_tx_er(onegbe_test_one_gbe_mac_gmii_tx_er),
    .gmii_txd(onegbe_test_one_gbe_mac_gmii_tx_data),
    .gtpowergood(gbe_gtpowergood),
    .gtrefclk_n(onegbe_test_one_gbe_mgt_clk_n),
    .gtrefclk_out(gbe_mgt_clk),
    .gtrefclk_p(onegbe_test_one_gbe_mgt_clk_p),
    .independent_clock_bufg(clk_200),
    .mmcm_locked_out(gbe_mmcm_locked_out),
    .pma_reset_out(),
    .reset(sys_rst),
    .resetdone(onegbe_test_one_gbe_reset_done),
    .rxn(onegbe_test_one_gbe_sfp_rx_n),
    .rxp(onegbe_test_one_gbe_sfp_rx_p),
    .rxuserclk2_out(gbe_rxuserclk2_out),
    .rxuserclk_out(gbe_rxuserclk_out),
    .signal_detect(1),
    .status_vector(onegbe_test_one_gbe_phy_status),
    .txn(onegbe_test_one_gbe_sfp_tx_n),
    .txp(onegbe_test_one_gbe_sfp_tx_p),
    .userclk2_out(gbe_userclk2_out),
    .userclk_out(gbe_userclk_out)
  );

  // sw_reg: bitfield_snapshot/ss/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) onegbe_test_bitfield_snapshot_ss_ctrl (
    .IP_BUS(onegbe_test_bitfield_snapshot_ss_ctrl_out),
    .IP_BUS_VALID(onegbe_test_bitfield_snapshot_ss_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(onegbe_test_bitfield_snapshot_ss_ctrl_user_data_out)
  );

  // sw_reg: bitfield_snapshot/ss/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) onegbe_test_bitfield_snapshot_ss_status (
    .IP_BUS(onegbe_test_bitfield_snapshot_ss_status_user_data_in),
    .IP_BUS_VALID(1'b01),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(onegbe_test_bitfield_snapshot_ss_status_in)
  );

  // sw_reg: dest_ip
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) onegbe_test_dest_ip (
    .IP_BUS(onegbe_test_dest_ip_out),
    .IP_BUS_VALID(onegbe_test_dest_ip_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(onegbe_test_dest_ip_user_data_out)
  );

  // sw_reg: dest_port
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) onegbe_test_dest_port (
    .IP_BUS(onegbe_test_dest_port_out),
    .IP_BUS_VALID(onegbe_test_dest_port_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(onegbe_test_dest_port_user_data_out)
  );

  // sw_reg: pkt_sim/enable
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) onegbe_test_pkt_sim_enable (
    .IP_BUS(onegbe_test_pkt_sim_enable_out),
    .IP_BUS_VALID(onegbe_test_pkt_sim_enable_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(onegbe_test_pkt_sim_enable_user_data_out)
  );

  // sw_reg: pkt_sim/payload_len
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) onegbe_test_pkt_sim_payload_len (
    .IP_BUS(onegbe_test_pkt_sim_payload_len_out),
    .IP_BUS_VALID(onegbe_test_pkt_sim_payload_len_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(onegbe_test_pkt_sim_payload_len_user_data_out)
  );

  // sw_reg: pkt_sim/period
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) onegbe_test_pkt_sim_period (
    .IP_BUS(onegbe_test_pkt_sim_period_out),
    .IP_BUS_VALID(onegbe_test_pkt_sim_period_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(onegbe_test_pkt_sim_period_user_data_out)
  );

  // sw_reg: rst
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) onegbe_test_rst (
    .IP_BUS(onegbe_test_rst_out),
    .IP_BUS_VALID(onegbe_test_rst_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(onegbe_test_rst_user_data_out)
  );

  // sys_block: xps:sys_block0
  axi4lite_ic_wrapper  axi4lite_interconnect (
    .axi4lite_aclk(axil_clk),
    .axi4lite_aresetn(axil_rst_n),
    .axi4lite_bitfield_snapshot_ss_bram_bitfield_snapshot_ss_bram_add(onegbe_test_bitfield_snapshot_ss_bram_addr),
    .axi4lite_bitfield_snapshot_ss_bram_bitfield_snapshot_ss_bram_clk(user_clk),
    .axi4lite_bitfield_snapshot_ss_bram_bitfield_snapshot_ss_bram_data_in(onegbe_test_bitfield_snapshot_ss_bram_data_in),
    .axi4lite_bitfield_snapshot_ss_bram_bitfield_snapshot_ss_bram_data_out(onegbe_test_bitfield_snapshot_ss_bram_data_out),
    .axi4lite_bitfield_snapshot_ss_bram_bitfield_snapshot_ss_bram_en(1'b1),
    .axi4lite_bitfield_snapshot_ss_bram_bitfield_snapshot_ss_bram_we(onegbe_test_bitfield_snapshot_ss_bram_we),
    .axi4lite_one_gbe_one_gbe_out(onegbe_test_one_gbe_out),
    .axi4lite_one_gbe_one_gbe_out_we(onegbe_test_one_gbe_out_we),
    .axi4lite_sw_reg_bitfield_snapshot_ss_ctrl_out(onegbe_test_bitfield_snapshot_ss_ctrl_out),
    .axi4lite_sw_reg_bitfield_snapshot_ss_ctrl_out_we(onegbe_test_bitfield_snapshot_ss_ctrl_out_we),
    .axi4lite_sw_reg_bitfield_snapshot_ss_status_in(onegbe_test_bitfield_snapshot_ss_status_in),
    .axi4lite_sw_reg_bitfield_snapshot_ss_status_in_we(onegbe_test_bitfield_snapshot_ss_status_in_we),
    .axi4lite_sw_reg_dest_ip_out(onegbe_test_dest_ip_out),
    .axi4lite_sw_reg_dest_ip_out_we(onegbe_test_dest_ip_out_we),
    .axi4lite_sw_reg_dest_port_out(onegbe_test_dest_port_out),
    .axi4lite_sw_reg_dest_port_out_we(onegbe_test_dest_port_out_we),
    .axi4lite_sw_reg_pkt_sim_enable_out(onegbe_test_pkt_sim_enable_out),
    .axi4lite_sw_reg_pkt_sim_enable_out_we(onegbe_test_pkt_sim_enable_out_we),
    .axi4lite_sw_reg_pkt_sim_payload_len_out(onegbe_test_pkt_sim_payload_len_out),
    .axi4lite_sw_reg_pkt_sim_payload_len_out_we(onegbe_test_pkt_sim_payload_len_out_we),
    .axi4lite_sw_reg_pkt_sim_period_out(onegbe_test_pkt_sim_period_out),
    .axi4lite_sw_reg_pkt_sim_period_out_we(onegbe_test_pkt_sim_period_out_we),
    .axi4lite_sw_reg_rst_out(onegbe_test_rst_out),
    .axi4lite_sw_reg_rst_out_we(onegbe_test_rst_out_we),
    .axi4lite_sys_block_sys_board_id_in(onegbe_test_sys_board_id_in),
    .axi4lite_sys_block_sys_board_id_in_we(onegbe_test_sys_board_id_in_we),
    .axi4lite_sys_block_sys_clkcounter_in(onegbe_test_sys_clkcounter_in),
    .axi4lite_sys_block_sys_clkcounter_in_we(onegbe_test_sys_clkcounter_in_we),
    .axi4lite_sys_block_sys_rev_in(onegbe_test_sys_rev_in),
    .axi4lite_sys_block_sys_rev_in_we(onegbe_test_sys_rev_in_we),
    .axi4lite_sys_block_sys_rev_rcs_in(onegbe_test_sys_rev_rcs_in),
    .axi4lite_sys_block_sys_rev_rcs_in_we(onegbe_test_sys_rev_rcs_in_we),
    .axi4lite_sys_block_sys_scratchpad_out(onegbe_test_sys_scratchpad_out),
    .axi4lite_sys_block_sys_scratchpad_out_we(onegbe_test_sys_scratchpad_out_we),
    .s_axi4lite_araddr(M_AXI_araddr[31:0]),
    .s_axi4lite_arready(M_AXI_arready),
    .s_axi4lite_arvalid(M_AXI_arvalid),
    .s_axi4lite_awaddr(M_AXI_awaddr[31:0]),
    .s_axi4lite_awready(M_AXI_awready),
    .s_axi4lite_awvalid(M_AXI_awvalid),
    .s_axi4lite_bready(M_AXI_bready),
    .s_axi4lite_bresp(M_AXI_bresp),
    .s_axi4lite_bvalid(M_AXI_bvalid),
    .s_axi4lite_rdata(M_AXI_rdata),
    .s_axi4lite_rready(M_AXI_rready),
    .s_axi4lite_rresp(M_AXI_rresp),
    .s_axi4lite_rvalid(M_AXI_rvalid),
    .s_axi4lite_wdata(M_AXI_wdata),
    .s_axi4lite_wready(M_AXI_wready),
    .s_axi4lite_wstrb(M_AXI_wstrb),
    .s_axi4lite_wvalid(M_AXI_wvalid)
  );


  onegbe_test  onegbe_test_inst (
    .clk(user_clk),
    .onegbe_test_bitfield_snapshot_ss_bram_addr(onegbe_test_bitfield_snapshot_ss_bram_addr),
    .onegbe_test_bitfield_snapshot_ss_bram_data_in(onegbe_test_bitfield_snapshot_ss_bram_data_in),
    .onegbe_test_bitfield_snapshot_ss_bram_data_out(onegbe_test_bitfield_snapshot_ss_bram_data_out),
    .onegbe_test_bitfield_snapshot_ss_bram_we(onegbe_test_bitfield_snapshot_ss_bram_we),
    .onegbe_test_bitfield_snapshot_ss_ctrl_user_data_out(onegbe_test_bitfield_snapshot_ss_ctrl_user_data_out),
    .onegbe_test_bitfield_snapshot_ss_status_user_data_in(onegbe_test_bitfield_snapshot_ss_status_user_data_in),
    .onegbe_test_dest_ip_user_data_out(onegbe_test_dest_ip_user_data_out),
    .onegbe_test_dest_port_user_data_out(onegbe_test_dest_port_user_data_out),
    .onegbe_test_one_gbe_app_dbg_data(onegbe_test_one_gbe_app_dbg_data),
    .onegbe_test_one_gbe_app_dbg_dvld(onegbe_test_one_gbe_app_dbg_dvld),
    .onegbe_test_one_gbe_app_rx_ack(onegbe_test_one_gbe_app_rx_ack),
    .onegbe_test_one_gbe_app_rx_badframe(onegbe_test_one_gbe_app_rx_badframe),
    .onegbe_test_one_gbe_app_rx_data(onegbe_test_one_gbe_app_rx_data),
    .onegbe_test_one_gbe_app_rx_dvld(onegbe_test_one_gbe_app_rx_dvld),
    .onegbe_test_one_gbe_app_rx_eof(onegbe_test_one_gbe_app_rx_eof),
    .onegbe_test_one_gbe_app_rx_overrun(onegbe_test_one_gbe_app_rx_overrun),
    .onegbe_test_one_gbe_app_rx_rst(onegbe_test_one_gbe_app_rx_rst),
    .onegbe_test_one_gbe_app_rx_srcip(onegbe_test_one_gbe_app_rx_srcip),
    .onegbe_test_one_gbe_app_rx_srcport(onegbe_test_one_gbe_app_rx_srcport),
    .onegbe_test_one_gbe_app_tx_afull(onegbe_test_one_gbe_app_tx_afull),
    .onegbe_test_one_gbe_app_tx_data(onegbe_test_one_gbe_app_tx_data),
    .onegbe_test_one_gbe_app_tx_destip(onegbe_test_one_gbe_app_tx_destip),
    .onegbe_test_one_gbe_app_tx_destport(onegbe_test_one_gbe_app_tx_destport),
    .onegbe_test_one_gbe_app_tx_dvld(onegbe_test_one_gbe_app_tx_dvld),
    .onegbe_test_one_gbe_app_tx_eof(onegbe_test_one_gbe_app_tx_eof),
    .onegbe_test_one_gbe_app_tx_overflow(onegbe_test_one_gbe_app_tx_overflow),
    .onegbe_test_one_gbe_app_tx_rst(onegbe_test_one_gbe_app_tx_rst),
    .onegbe_test_pkt_sim_enable_user_data_out(onegbe_test_pkt_sim_enable_user_data_out),
    .onegbe_test_pkt_sim_payload_len_user_data_out(onegbe_test_pkt_sim_payload_len_user_data_out),
    .onegbe_test_pkt_sim_period_user_data_out(onegbe_test_pkt_sim_period_user_data_out),
    .onegbe_test_rst_user_data_out(onegbe_test_rst_user_data_out)
  );

  // zcu111: ZCU111
  zcu111_infrastructure #(
    .DIVCLK(1),
    .DIVIDE(4.0),
    .MULTIPLY(8.0)
  ) zcu111_infr_inst (
    .clk_100_n(clk_100_n),
    .clk_100_p(clk_100_p),
    .sys_clk(sys_clk),
    .sys_clk180(sys_clk180),
    .sys_clk270(sys_clk270),
    .sys_clk90(sys_clk90),
    .sys_clk_rst(sys_clk_rst)
  );


  zcu111  zcu111_inst (
    .M_AXI_RFDC_araddr(M_AXI_RFDC_araddr),
    .M_AXI_RFDC_arprot(M_AXI_RFDC_arprot),
    .M_AXI_RFDC_arready(M_AXI_RFDC_arready),
    .M_AXI_RFDC_arvalid(M_AXI_RFDC_arvalid),
    .M_AXI_RFDC_awaddr(M_AXI_RFDC_awaddr),
    .M_AXI_RFDC_awprot(M_AXI_RFDC_awprot),
    .M_AXI_RFDC_awready(M_AXI_RFDC_awready),
    .M_AXI_RFDC_awvalid(M_AXI_RFDC_awvalid),
    .M_AXI_RFDC_bready(M_AXI_RFDC_bready),
    .M_AXI_RFDC_bresp(M_AXI_RFDC_bresp),
    .M_AXI_RFDC_bvalid(M_AXI_RFDC_bvalid),
    .M_AXI_RFDC_rdata(M_AXI_RFDC_rdata),
    .M_AXI_RFDC_rready(M_AXI_RFDC_rready),
    .M_AXI_RFDC_rresp(M_AXI_RFDC_rresp),
    .M_AXI_RFDC_rvalid(M_AXI_RFDC_rvalid),
    .M_AXI_RFDC_wdata(M_AXI_RFDC_wdata),
    .M_AXI_RFDC_wready(M_AXI_RFDC_wready),
    .M_AXI_RFDC_wstrb(M_AXI_RFDC_wstrb),
    .M_AXI_RFDC_wvalid(M_AXI_RFDC_wvalid),
    .M_AXI_araddr(M_AXI_araddr),
    .M_AXI_arprot(M_AXI_arprot),
    .M_AXI_arready(M_AXI_arready),
    .M_AXI_arvalid(M_AXI_arvalid),
    .M_AXI_awaddr(M_AXI_awaddr),
    .M_AXI_awprot(M_AXI_awprot),
    .M_AXI_awready(M_AXI_awready),
    .M_AXI_awvalid(M_AXI_awvalid),
    .M_AXI_bready(M_AXI_bready),
    .M_AXI_bresp(M_AXI_bresp),
    .M_AXI_bvalid(M_AXI_bvalid),
    .M_AXI_rdata(M_AXI_rdata),
    .M_AXI_rready(M_AXI_rready),
    .M_AXI_rresp(M_AXI_rresp),
    .M_AXI_rvalid(M_AXI_rvalid),
    .M_AXI_wdata(M_AXI_wdata),
    .M_AXI_wready(M_AXI_wready),
    .M_AXI_wstrb(M_AXI_wstrb),
    .M_AXI_wvalid(M_AXI_wvalid),
    .axil_clk(axil_clk),
    .axil_rst(axil_rst),
    .axil_rst_n(axil_rst_n)
  );


/*
                   _                                  _       
     /\           (_)                                | |      
    /  \   ___ ___ _  __ _ _ __  _ __ ___   ___ _ __ | |_ ___ 
   / /\ \ / __/ __| |/ _` | '_ \| '_ ` _ \ / _ \ '_ \| __/ __|
  / ____ \\__ \__ \ | (_| | | | | | | | | |  __/ | | | |_\__ \ 
 /_/    \_\___/___/_|\__, |_| |_|_| |_| |_|\___|_| |_|\__|___/
                      __/ |                                   
                     |___/                                    
*/
  // xsg: ZCU111
  assign user_clk = sys_clk;
  assign user_clk180 = sys_clk180;
  assign user_clk270 = sys_clk270;
  assign user_clk90 = sys_clk90;


endmodule