set_property PACKAGE_PIN Y35 [get_ports onegbe_test_one_gbe_sfp_tx_p]
set_property PACKAGE_PIN Y36 [get_ports onegbe_test_one_gbe_sfp_tx_n]
set_property PACKAGE_PIN AA38 [get_ports onegbe_test_one_gbe_sfp_rx_p]
set_property PACKAGE_PIN AA39 [get_ports onegbe_test_one_gbe_sfp_rx_n]
set_property PACKAGE_PIN Y31 [get_ports onegbe_test_one_gbe_mgt_clk_p]
set_property PACKAGE_PIN Y32 [get_ports onegbe_test_one_gbe_mgt_clk_n]
set_property PACKAGE_PIN AL16 [get_ports clk_100_p]
set_property IOSTANDARD LVDS [get_ports clk_100_p]
create_clock -period 7.812 -name clk_100_p -waveform {0.000 3.906} [get_ports {clk_100_p}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins zcu111_infr_inst/user_clk_mmcm_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins zcu111_inst/zynq_ultra_ps_e_0/U0/PS8_i/PLCLK[0]]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins zcu111_inst/zynq_ultra_ps_e_0/U0/PS8_i/PLCLK[0]]] -group [get_clocks -of_objects [get_pins zcu111_infr_inst/user_clk_mmcm_inst/CLKOUT0]]
