# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tx_fifo_ext/tx_fifo_ext.xci
# IP: The module: 'tx_fifo_ext' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tx_fifo_ext/tx_fifo_ext.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo_ext'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tx_fifo_ext/tx_fifo_ext_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo_ext'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tx_fifo_ext/tx_fifo_ext.xci
# IP: The module: 'tx_fifo_ext' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tx_fifo_ext/tx_fifo_ext.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo_ext'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/tengbe_test/tengbe_test/myproj/myproj.srcs/sources_1/ip/tx_fifo_ext/tx_fifo_ext_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo_ext'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
