# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/gig_ethernet_pcs_pma_autonegotiation_1000BASEX.xci
# IP: The module: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/ip_0/PCS_PMA_gig_ethernet_pcs_pma_1_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCS_PMA_gig_ethernet_pcs_pma_1_0_gt || ORIG_REF_NAME==PCS_PMA_gig_ethernet_pcs_pma_1_0_gt} -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/ip_0/synth/PCS_PMA_gig_ethernet_pcs_pma_1_0_gt_ooc.xdc

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/ip_0/synth/PCS_PMA_gig_ethernet_pcs_pma_1_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCS_PMA_gig_ethernet_pcs_pma_1_0_gt || ORIG_REF_NAME==PCS_PMA_gig_ethernet_pcs_pma_1_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/gig_ethernet_pcs_pma_autonegotiation_1000BASEX_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/synth/gig_ethernet_pcs_pma_autonegotiation_1000BASEX.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/synth/gig_ethernet_pcs_pma_autonegotiation_1000BASEX_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/synth/gig_ethernet_pcs_pma_autonegotiation_1000BASEX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/gig_ethernet_pcs_pma_autonegotiation_1000BASEX.xci
# IP: The module: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/ip_0/PCS_PMA_gig_ethernet_pcs_pma_1_0_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCS_PMA_gig_ethernet_pcs_pma_1_0_gt || ORIG_REF_NAME==PCS_PMA_gig_ethernet_pcs_pma_1_0_gt} -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/ip_0/synth/PCS_PMA_gig_ethernet_pcs_pma_1_0_gt_ooc.xdc

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/ip_0/synth/PCS_PMA_gig_ethernet_pcs_pma_1_0_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCS_PMA_gig_ethernet_pcs_pma_1_0_gt || ORIG_REF_NAME==PCS_PMA_gig_ethernet_pcs_pma_1_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/gig_ethernet_pcs_pma_autonegotiation_1000BASEX_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/synth/gig_ethernet_pcs_pma_autonegotiation_1000BASEX.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/synth/gig_ethernet_pcs_pma_autonegotiation_1000BASEX_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/raw_axi_test/onegbe_test/onegbe_test/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_autonegotiation_1000BASEX/synth/gig_ethernet_pcs_pma_autonegotiation_1000BASEX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_autonegotiation_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
