# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_cores/mode1_test/rfdc_multi_cores_mode1/myproj/myproj.srcs/sources_1/bd/zcu111/ip/zcu111_proc_sys_reset_0_0/zcu111_proc_sys_reset_0_0.xci
# IP: The module: 'zcu111_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_cores/mode1_test/rfdc_multi_cores_mode1/myproj/myproj.srcs/sources_1/bd/zcu111/ip/zcu111_proc_sys_reset_0_0/zcu111_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu111_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_cores/mode1_test/rfdc_multi_cores_mode1/myproj/myproj.srcs/sources_1/bd/zcu111/ip/zcu111_proc_sys_reset_0_0/zcu111_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu111_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_cores/mode1_test/rfdc_multi_cores_mode1/myproj/myproj.srcs/sources_1/bd/zcu111/ip/zcu111_proc_sys_reset_0_0/zcu111_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu111_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_cores/mode1_test/rfdc_multi_cores_mode1/myproj/myproj.srcs/sources_1/bd/zcu111/ip/zcu111_proc_sys_reset_0_0/zcu111_proc_sys_reset_0_0.xci
# IP: The module: 'zcu111_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_cores/mode1_test/rfdc_multi_cores_mode1/myproj/myproj.srcs/sources_1/bd/zcu111/ip/zcu111_proc_sys_reset_0_0/zcu111_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu111_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_cores/mode1_test/rfdc_multi_cores_mode1/myproj/myproj.srcs/sources_1/bd/zcu111/ip/zcu111_proc_sys_reset_0_0/zcu111_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu111_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wei/casper/casper_mlib/tutorials_devel/zcu111/rfdc_multi_cores/mode1_test/rfdc_multi_cores_mode1/myproj/myproj.srcs/sources_1/bd/zcu111/ip/zcu111_proc_sys_reset_0_0/zcu111_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu111_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
