// MODULE top, AUTOMATICALLY GENERATED BY PYTHON

/**/
`default_nettype wire


module top (
  // zcu111: ZCU111
    input clk_100_n,
    input clk_100_p
  );




/*
  _____ _                   _     
 / ____(_)                 | |    
| (___  _  __ _ _ __   __ _| |___ 
 \___ \| |/ _` | '_ \ / _` | / __|
 ____) | | (_| | | | | (_| | \__ \ 
|_____/|_|\__, |_| |_|\__,_|_|___/
          __/ |                  
         |___/                   
*/
  // raxi: raw_from_processor
  wire axil_clk;
  wire axil_rst_n;
  wire [31:0] m_axi4lite_raw_from_processor_araddr;
  wire [0:0] m_axi4lite_raw_from_processor_arready;
  wire [0:0] m_axi4lite_raw_from_processor_arvalid;
  wire [31:0] m_axi4lite_raw_from_processor_awaddr;
  wire [0:0] m_axi4lite_raw_from_processor_awready;
  wire [0:0] m_axi4lite_raw_from_processor_awvalid;
  wire [0:0] m_axi4lite_raw_from_processor_bready;
  wire [1:0] m_axi4lite_raw_from_processor_bresp;
  wire [0:0] m_axi4lite_raw_from_processor_bvalid;
  wire [31:0] m_axi4lite_raw_from_processor_rdata;
  wire [0:0] m_axi4lite_raw_from_processor_rready;
  wire [1:0] m_axi4lite_raw_from_processor_rresp;
  wire [0:0] m_axi4lite_raw_from_processor_rvalid;
  wire [31:0] m_axi4lite_raw_from_processor_wdata;
  wire [0:0] m_axi4lite_raw_from_processor_wready;
  wire [3:0] m_axi4lite_raw_from_processor_wstrb;
  wire [0:0] m_axi4lite_raw_from_processor_wvalid;
  wire [31:0] reg_test_raw_from_processor_user_data_out;
  // sw_reg: software_register
  wire [31:0] reg_test_software_register_in;
  wire [31:0] reg_test_software_register_user_data_in;
  // sys_block: xps:sys_block0
  wire [0:0] reg_test_software_register_in_we;
  wire [31:0] reg_test_sys_board_id_in;
  wire [0:0] reg_test_sys_board_id_in_we;
  wire [31:0] reg_test_sys_clkcounter_in;
  wire [0:0] reg_test_sys_clkcounter_in_we;
  wire [31:0] reg_test_sys_rev_in;
  wire [0:0] reg_test_sys_rev_in_we;
  wire [31:0] reg_test_sys_rev_rcs_in;
  wire [0:0] reg_test_sys_rev_rcs_in_we;
  wire [31:0] reg_test_sys_scratchpad_out;
  wire [0:0] reg_test_sys_scratchpad_out_we;
  // xsg: ZCU111
  wire user_clk;
  wire user_clk180;
  wire user_clk270;
  wire user_clk90;
  // zcu111: ZCU111
  wire [39:0] M_AXI_RFDC_araddr;
  wire [2:0] M_AXI_RFDC_arprot;
  wire M_AXI_RFDC_arready;
  wire M_AXI_RFDC_arvalid;
  wire [39:0] M_AXI_RFDC_awaddr;
  wire [2:0] M_AXI_RFDC_awprot;
  wire M_AXI_RFDC_awready;
  wire M_AXI_RFDC_awvalid;
  wire M_AXI_RFDC_bready;
  wire [1:0] M_AXI_RFDC_bresp;
  wire M_AXI_RFDC_bvalid;
  wire [31:0] M_AXI_RFDC_rdata;
  wire M_AXI_RFDC_rready;
  wire [1:0] M_AXI_RFDC_rresp;
  wire M_AXI_RFDC_rvalid;
  wire [31:0] M_AXI_RFDC_wdata;
  wire M_AXI_RFDC_wready;
  wire [3:0] M_AXI_RFDC_wstrb;
  wire M_AXI_RFDC_wvalid;
  wire [39:0] M_AXI_araddr;
  wire [2:0] M_AXI_arprot;
  wire M_AXI_arready;
  wire M_AXI_arvalid;
  wire [39:0] M_AXI_awaddr;
  wire [2:0] M_AXI_awprot;
  wire M_AXI_awready;
  wire M_AXI_awvalid;
  wire M_AXI_bready;
  wire [1:0] M_AXI_bresp;
  wire M_AXI_bvalid;
  wire [31:0] M_AXI_rdata;
  wire M_AXI_rready;
  wire [1:0] M_AXI_rresp;
  wire M_AXI_rvalid;
  wire [31:0] M_AXI_wdata;
  wire M_AXI_wready;
  wire [3:0] M_AXI_wstrb;
  wire M_AXI_wvalid;
  wire axil_rst;
  wire clk_200;
  wire sys_clk;
  wire sys_clk180;
  wire sys_clk270;
  wire sys_clk90;
  wire sys_clk_rst;

/*
  _____           _                            
 |_   _|         | |                           
   | |  _ __  ___| |_ __ _ _ __   ___ ___  ___ 
   | | | '_ \/ __| __/ _` | '_ \ / __/ _ \/ __|
  _| |_| | | \__ \ || (_| | | | | (_|  __/\__ \ 
 |_____|_| |_|___/\__\__,_|_| |_|\___\___||___/
*/
  // raxi: raw_from_processor
  raw_axi4lite_slave  reg_test_raw_from_processor (
    .axi4lite_aclk(axil_clk),
    .axi4lite_aresetn(axil_rst_n),
    .s_axi4lite_araddr(m_axi4lite_raw_from_processor_araddr),
    .s_axi4lite_arready(m_axi4lite_raw_from_processor_arready),
    .s_axi4lite_arvalid(m_axi4lite_raw_from_processor_arvalid),
    .s_axi4lite_awaddr(m_axi4lite_raw_from_processor_awaddr),
    .s_axi4lite_awready(m_axi4lite_raw_from_processor_awready),
    .s_axi4lite_awvalid(m_axi4lite_raw_from_processor_awvalid),
    .s_axi4lite_bready(m_axi4lite_raw_from_processor_bready),
    .s_axi4lite_bresp(m_axi4lite_raw_from_processor_bresp),
    .s_axi4lite_bvalid(m_axi4lite_raw_from_processor_bvalid),
    .s_axi4lite_rdata(m_axi4lite_raw_from_processor_rdata),
    .s_axi4lite_rready(m_axi4lite_raw_from_processor_rready),
    .s_axi4lite_rresp(m_axi4lite_raw_from_processor_rresp),
    .s_axi4lite_rvalid(m_axi4lite_raw_from_processor_rvalid),
    .s_axi4lite_wdata(m_axi4lite_raw_from_processor_wdata),
    .s_axi4lite_wready(m_axi4lite_raw_from_processor_wready),
    .s_axi4lite_wstrb(m_axi4lite_raw_from_processor_wstrb),
    .s_axi4lite_wvalid(m_axi4lite_raw_from_processor_wvalid),
    .user_data_out(reg_test_raw_from_processor_user_data_out)
  );

  // sw_reg: software_register
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) reg_test_software_register (
    .IP_BUS(reg_test_software_register_user_data_in),
    .IP_BUS_VALID(1'b01),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(reg_test_software_register_in)
  );

  // sys_block: xps:sys_block0
  axi4lite_ic_wrapper  axi4lite_interconnect (
    .axi4lite_aclk(axil_clk),
    .axi4lite_aresetn(axil_rst_n),
    .axi4lite_sw_reg_software_register_in(reg_test_software_register_in),
    .axi4lite_sw_reg_software_register_in_we(reg_test_software_register_in_we),
    .axi4lite_sys_block_sys_board_id_in(reg_test_sys_board_id_in),
    .axi4lite_sys_block_sys_board_id_in_we(reg_test_sys_board_id_in_we),
    .axi4lite_sys_block_sys_clkcounter_in(reg_test_sys_clkcounter_in),
    .axi4lite_sys_block_sys_clkcounter_in_we(reg_test_sys_clkcounter_in_we),
    .axi4lite_sys_block_sys_rev_in(reg_test_sys_rev_in),
    .axi4lite_sys_block_sys_rev_in_we(reg_test_sys_rev_in_we),
    .axi4lite_sys_block_sys_rev_rcs_in(reg_test_sys_rev_rcs_in),
    .axi4lite_sys_block_sys_rev_rcs_in_we(reg_test_sys_rev_rcs_in_we),
    .axi4lite_sys_block_sys_scratchpad_out(reg_test_sys_scratchpad_out),
    .axi4lite_sys_block_sys_scratchpad_out_we(reg_test_sys_scratchpad_out_we),
    .m_axi4lite_raw_from_processor_araddr(m_axi4lite_raw_from_processor_araddr),
    .m_axi4lite_raw_from_processor_arready(m_axi4lite_raw_from_processor_arready),
    .m_axi4lite_raw_from_processor_arvalid(m_axi4lite_raw_from_processor_arvalid),
    .m_axi4lite_raw_from_processor_awaddr(m_axi4lite_raw_from_processor_awaddr),
    .m_axi4lite_raw_from_processor_awready(m_axi4lite_raw_from_processor_awready),
    .m_axi4lite_raw_from_processor_awvalid(m_axi4lite_raw_from_processor_awvalid),
    .m_axi4lite_raw_from_processor_bready(m_axi4lite_raw_from_processor_bready),
    .m_axi4lite_raw_from_processor_bresp(m_axi4lite_raw_from_processor_bresp),
    .m_axi4lite_raw_from_processor_bvalid(m_axi4lite_raw_from_processor_bvalid),
    .m_axi4lite_raw_from_processor_rdata(m_axi4lite_raw_from_processor_rdata),
    .m_axi4lite_raw_from_processor_rready(m_axi4lite_raw_from_processor_rready),
    .m_axi4lite_raw_from_processor_rresp(m_axi4lite_raw_from_processor_rresp),
    .m_axi4lite_raw_from_processor_rvalid(m_axi4lite_raw_from_processor_rvalid),
    .m_axi4lite_raw_from_processor_wdata(m_axi4lite_raw_from_processor_wdata),
    .m_axi4lite_raw_from_processor_wready(m_axi4lite_raw_from_processor_wready),
    .m_axi4lite_raw_from_processor_wstrb(m_axi4lite_raw_from_processor_wstrb),
    .m_axi4lite_raw_from_processor_wvalid(m_axi4lite_raw_from_processor_wvalid),
    .s_axi4lite_araddr(M_AXI_araddr),
    .s_axi4lite_arready(M_AXI_arready),
    .s_axi4lite_arvalid(M_AXI_arvalid),
    .s_axi4lite_awaddr(M_AXI_awaddr),
    .s_axi4lite_awready(M_AXI_awready),
    .s_axi4lite_awvalid(M_AXI_awvalid),
    .s_axi4lite_bready(M_AXI_bready),
    .s_axi4lite_bresp(M_AXI_bresp),
    .s_axi4lite_bvalid(M_AXI_bvalid),
    .s_axi4lite_rdata(M_AXI_rdata),
    .s_axi4lite_rready(M_AXI_rready),
    .s_axi4lite_rresp(M_AXI_rresp),
    .s_axi4lite_rvalid(M_AXI_rvalid),
    .s_axi4lite_wdata(M_AXI_wdata),
    .s_axi4lite_wready(M_AXI_wready),
    .s_axi4lite_wstrb(M_AXI_wstrb),
    .s_axi4lite_wvalid(M_AXI_wvalid)
  );


  reg_test  reg_test_inst (
    .clk(user_clk),
    .reg_test_raw_from_processor_user_data_out(reg_test_raw_from_processor_user_data_out),
    .reg_test_software_register_user_data_in(reg_test_software_register_user_data_in)
  );

  // zcu111: ZCU111
  zcu111_infrastructure #(
    .DIVCLK(1),
    .DIVIDE(4.0),
    .MULTIPLY(8.0)
  ) zcu111_infr_inst (
    .clk_100_n(clk_100_n),
    .clk_100_p(clk_100_p),
    .clk_200(clk_200),
    .sys_clk(sys_clk),
    .sys_clk180(sys_clk180),
    .sys_clk270(sys_clk270),
    .sys_clk90(sys_clk90),
    .sys_clk_rst(sys_clk_rst)
  );


  zcu111  zcu111_inst (
    .M_AXI_RFDC_araddr(M_AXI_RFDC_araddr),
    .M_AXI_RFDC_arprot(M_AXI_RFDC_arprot),
    .M_AXI_RFDC_arready(M_AXI_RFDC_arready),
    .M_AXI_RFDC_arvalid(M_AXI_RFDC_arvalid),
    .M_AXI_RFDC_awaddr(M_AXI_RFDC_awaddr),
    .M_AXI_RFDC_awprot(M_AXI_RFDC_awprot),
    .M_AXI_RFDC_awready(M_AXI_RFDC_awready),
    .M_AXI_RFDC_awvalid(M_AXI_RFDC_awvalid),
    .M_AXI_RFDC_bready(M_AXI_RFDC_bready),
    .M_AXI_RFDC_bresp(M_AXI_RFDC_bresp),
    .M_AXI_RFDC_bvalid(M_AXI_RFDC_bvalid),
    .M_AXI_RFDC_rdata(M_AXI_RFDC_rdata),
    .M_AXI_RFDC_rready(M_AXI_RFDC_rready),
    .M_AXI_RFDC_rresp(M_AXI_RFDC_rresp),
    .M_AXI_RFDC_rvalid(M_AXI_RFDC_rvalid),
    .M_AXI_RFDC_wdata(M_AXI_RFDC_wdata),
    .M_AXI_RFDC_wready(M_AXI_RFDC_wready),
    .M_AXI_RFDC_wstrb(M_AXI_RFDC_wstrb),
    .M_AXI_RFDC_wvalid(M_AXI_RFDC_wvalid),
    .M_AXI_araddr(M_AXI_araddr),
    .M_AXI_arprot(M_AXI_arprot),
    .M_AXI_arready(M_AXI_arready),
    .M_AXI_arvalid(M_AXI_arvalid),
    .M_AXI_awaddr(M_AXI_awaddr),
    .M_AXI_awprot(M_AXI_awprot),
    .M_AXI_awready(M_AXI_awready),
    .M_AXI_awvalid(M_AXI_awvalid),
    .M_AXI_bready(M_AXI_bready),
    .M_AXI_bresp(M_AXI_bresp),
    .M_AXI_bvalid(M_AXI_bvalid),
    .M_AXI_rdata(M_AXI_rdata),
    .M_AXI_rready(M_AXI_rready),
    .M_AXI_rresp(M_AXI_rresp),
    .M_AXI_rvalid(M_AXI_rvalid),
    .M_AXI_wdata(M_AXI_wdata),
    .M_AXI_wready(M_AXI_wready),
    .M_AXI_wstrb(M_AXI_wstrb),
    .M_AXI_wvalid(M_AXI_wvalid),
    .axil_clk(axil_clk),
    .axil_rst(axil_rst),
    .axil_rst_n(axil_rst_n)
  );


/*
                   _                                  _       
     /\           (_)                                | |      
    /  \   ___ ___ _  __ _ _ __  _ __ ___   ___ _ __ | |_ ___ 
   / /\ \ / __/ __| |/ _` | '_ \| '_ ` _ \ / _ \ '_ \| __/ __|
  / ____ \\__ \__ \ | (_| | | | | | | | | |  __/ | | | |_\__ \ 
 /_/    \_\___/___/_|\__, |_| |_|_| |_| |_|\___|_| |_|\__|___/
                      __/ |                                   
                     |___/                                    
*/
  // xsg: ZCU111
  assign user_clk = sys_clk;
  assign user_clk180 = sys_clk180;
  assign user_clk270 = sys_clk270;
  assign user_clk90 = sys_clk90;


endmodule